### ISSUE TITLE
Missing systems-manager-samples

### ISSUE THREAD

**Issue by reidca** [aws-samples/aws-systems-manager-cloudformation-samples#2]
The readme mentions that there is a folder called systems-manager-samples. No such folder from what I can see.

**Comment by virtlima** [comment]
I will add an example and that folder and push it up.

**Comment by virtlima** [comment]
Added a Systems Manager Automation document that was used in [MGT416 ](https://reinvent2019.aws-management.tools/mgt416/en/mgt416.html) Session at reinvent 2019.
