### ISSUE TITLE
Would be great to have a Chef example

### ISSUE THREAD

**Issue by Colyn1337** [aws-samples/aws-systems-manager-cloudformation-samples#4]
The example templates are great but there isn't one for Chef

aws-systems-manager-cloudformation-samples/cloudformation-samples/

**Comment by virtlima** [comment]
We can work on crafting that  up, thanks for the feedback. In the interim here is a [blog post](https://aws.amazon.com/blogs/mt/how-to-execute-chef-recipes-using-aws-systems-manager/) that walk through doing that. We will turn that into an example in the this repo.

**Comment by virtlima** [comment]
A Chef example had been added to the repo
